num = int(input('digita um numero: '))

print('''escolha sua convercao: 
[1] converter para BINARIO
[2] converter para OCTAL
[3] converter para HEXADECIMAL  ''')

opcao = int(input('sua opcao: '))

if opcao == 1:
    print('{} convertido para BINARIO e igual a {}'.format(num, bin(num)[2:]))
elif opcao == 2:
    print('{} convertido para OCTAL e igual a {}'.format(num, oct(num)[2:]))
elif opcao == 3:
    print('{} convertido para HEXADECIMAL e igual a {}'.format(num, hex(num)[2:]))
else:
    print('OPCAO INVALIDA')